### ISSUE TITLE
Remove datetime module and use imandra-ptime directly

### ISSUE THREAD

**Issue by bronsa** [imandra-ai/itr-ast#6]
~~the datetime files got out of sync, we should just submodule fix-engine instead of copying over files manually~~

The same in fix-engine. We need a uniform API (in `imandra-ptime-util`?) that IPL can target for codegen.

**Comment by mattjbray** [comment]
I remember discussing this with @ewenmaclean - the idea is the copied datetime file is temporary and we should switch to using imandra-ptime directly.

I don't think itr-ast should depend on fix-engine. Unless there is some reason we need to use the same datetime and can't use imandra-ptime directly?

**Comment by mattjbray** [comment]
Hmm I guess it's because of the `duration` types and others? Maybe we can move all those to `imandra-ptime-util`? Unless they are fix-specific, in which case then yes the fix-engine dependency makes sense.

**Comment by bronsa** [comment]
ah I see. had a chat with @ewenmaclean yesterday but maybe I derailed the conversation then, did not realize `datetime` was supposed to be temporary. 

I guess we can move to ptime directly, `duration` is just a span I think? does ptime have encoders/decoders?

**Comment by ewenmaclean** [comment]
This is  resolved - the question of whether to remove Datetime from fix-engine (and do all truncating etc on parsing/encoding) should be moved there
